name: Basic Terraform Validations

on:
    pull_request:
      types:
        - opened
        - reopened
        - synchronize
        - ready_for_review
    workflow_dispatch:

        
jobs:
    # Retrive the changed directories from the PR
    build:
      name: Get changed directories
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v44
          with:
            dir_names: 'true'
            dir_names_exclude_current_dir: 'true' # exclude working dir as this won't be changed
            dir_names_max_depth: '5'
        - name: Terraform fmt
          id: terraform-fmt
          uses: dflook/terraform-fmt-check@v1
          with:
              path: ${{ steps.changed-files.outputs.dir_names }}

          